export const hasuraImportProfile = {
  tableName: 'report_project',
  mutationName: 'insert_report_project',
  objectTypeName: 'report_project_insert_input',
  fieldMappings: {
    项目编号: 'project_code',
    签订年: 'signing_year',
    项目编号申请时间: 'project_code_application_time',
    合同编号: 'contract_number',
    项目_设备名称: ['name', 'project_or_equipment_name'],
    负责部门: 'responsible_department',
    项目经理: 'project_manager',
    销售经理: 'sales_manager',
    合同性质: 'contract_type',
    客户名称: 'client_name',
    终端客户类型: 'end_customer_type',
    终端客户: 'end_customer',
    终端客户名称: 'end_customer_name',
    省份: 'province',
    市级: 'city',
    项目状态: 'project_status',
    验收单日期: 'acceptance_date',
    实际开工时间: 'actual_start_date',
    实施结束时间: 'implementation_end_date',
    质保期周期_单位年: 'warranty_period_years',
    是否收单验收: 'is_order_received',
    是否在质保期: 'is_within_warranty_period',
    运维截至日期: 'maintenance_end_date',
    合同金额_小写: 'contract_amount_lowercase',
    合同金额_大写: 'contract_amount_uppercase',
    税点: 'tax_rate',
    确认收入金额: 'confirmed_revenue_amount',
    运维方式: 'maintenance_method',
    售前负责人: 'pre_sales_responsible',
    运维负责人: 'operations_manager',
    销售类型: 'sales_type',
    备注: 'remarks',
    招投标方式: 'bidding_method',
    代理商: 'agent',
    销售状态: 'sales_status',
    技术协议: 'technical_agreement',
    合同要求起止时间: 'contract_duration',
    项目类型: 'project_type',
    地址: 'address',
  } as Record<string, string | string[]>,
}
